apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
spec:
  selector:
    matchLabels:
      name: orderer
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.5
          imagePullPolicy: IfNotPresent
          env:
             ##################
            - name: FABRIC_LOGGING_SPEC
              value: info
            # - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
            #   value: none
            - name: CONFIGTX_ORDERER_ADDRESSES
              value: "orderer:7050"
            # - name: ORDERER_GENERAL_BOOTSTRAPFILE
            #   value: none
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
            - name: ORDERER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            # - name: ORDERER_GENERAL_LOCALMSPDIR
            #   value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp

            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt]"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key

            
            - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
              value: none
            - name: ORDERER_METRICS_PROVIDER
              value: prometheus
            - name: ORDERER_CHANNELPARTICIPATION_ENABLED
              value: "true"
              ##New
            - name: ORDERER_FILELEDGER_LOCATION
              value: /organizations/ordererOrganizations/example.com/orderers/
              #### ADmin
            - name: ORDERER_ADMIN_TLS_ENABLED
              value: "true"
            # - name: ORDERER_ADMIN_TLS_CERTIFICATE
            #   value: /var/hyperledger/orderer/tls/server.crt
            # - name: ORDERER_ADMIN_TLS_PRIVATEKEY
            #   value: /var/hyperledger/orderer/tls/server.key
            # - name: ORDERER_ADMIN_TLS_ROOTCAS
            #   value: "[/var/hyperledger/orderer/tls/ca.crt]"
            # - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
            #   value: "[/var/hyperledger/orderer/tls/ca.crt]"

            # ////////////////////////////

            - name: ORDERER_ADMIN_TLS_CERTIFICATE
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            - name: ORDERER_ADMIN_TLS_PRIVATEKEY
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
            - name: ORDERER_ADMIN_TLS_ROOTCAS
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
            - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
              value: "[/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt]"
            - name: ORDERER_ADMIN_LISTENADDRESS
              value: 0.0.0.0:7053

            ########################################################

            # - name: ORDERER_GENERAL_LISTENADDRESS
            #   value: 0.0.0.0
            # - name: ORDERER_GENERAL_GENESISMETHOD
            #   value: file
            # - name: ORDERER_GENERAL_GENESISFILE
            #   value: /var/hyperledger/orderer/orderer.genesis.block
            # - name: ORDERER_GENERAL_LOCALMSPID
            #   value: OrdererMSP
            # - name: ORDERER_GENERAL_LOCALMSPDIR
            #   value: /var/hyperledger/orderer/msp
            # - name: ORDERER_GENERAL_TLS_ENABLED
            #   value: "true"
            # - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            #   value: /var/hyperledger/orderer/tls/server.key
            # - name: ORDERER_GENERAL_TLS_CERTIFICATE
            #   value: /var/hyperledger/orderer/tls/server.crt
            # - name: ORDERER_GENERAL_TLS_ROOTCAS
            #   value: "[/var/hyperledger/orderer/tls/ca.crt]"
            # - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            #   value: /var/hyperledger/orderer/tls/server.crt
            # - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            #   value: /var/hyperledger/orderer/tls/server.key
            # - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
            #   value: "[/var/hyperledger/orderer/tls/ca.crt]"

          # ports:
          #   - containerPort: 7050
          #   - containerPort: 9443
          #   - containerPort: 7053
          resources:
            limits:
              memory: "300Mi"
              cpu: "250m"
            requests:
              memory: "250Mi"
              cpu: "150m"

          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - name: fabricfiles
              mountPath: /channel-artifacts
              subPath: channel-artifacts
            - name: builders-config
              mountPath: /etc/hyperledger/fabric/orderer.yaml
              subPath: orderer.yaml
            - name: fabricfiles
              mountPath: /var/hyperledger/orderer/tls
              subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls
            - name: fabricfiles
              mountPath: /var/hyperledger/orderer/msp
              subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp

      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: mypvc
        - name: builders-config
          configMap:
            name: builders-config
            items:
              - key: orderer.yaml
                path: orderer.yaml
