kind: Service
apiVersion: v1
metadata:
  name: orderer
  labels:
    run: orderer
spec:
  selector:
    name: orderer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7050
      name: grpc
      targetPort: 7050
    - protocol: TCP
      port: 9443
      name: metrics
      targetPort: 9443
    - protocol: TCP
      port: 7053
      name: admin
      # targetPort: 7053
# # ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: orderer
#   labels:
#     run: orderer
#     k8s-app: orderer
# spec:
#   selector:
#     name: orderer
#   type: NodePort
#   ports:
#     - port: 7053
#       # protocol: TCP
#       targetPort: 7053
#       nodePort: 30000
