apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: nginx
      resources:
        limits:
          memory: "200Mi"
          cpu: "300m"
        requests:
          memory: "64Mi"
          cpu: "250m"

      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /usr/share/ngnix/html
          name: myvol
          subPath: test/
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc
      # nfs:
      # path: /data
      # server: 192.168.3.90
