apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/
    server: 10.10.34.44

  # nfs:
  #   path: /data
  #   server: 192.168.3.90
