apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-dealer
spec:
  selector:
    matchLabels:
      app: ca-dealer
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-dealer
    spec:
      containers:
        - name: ca-dealer
          image: hyperledger/fabric-ca:1.5.6
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          command:
            [
              "fabric-ca-server",
              "start",
              "-b",
              "admin:adminpw",
              "--port",
              "9054",
              "-d",
            ]
          env:
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-dealer
            - name: FABRIC_CA_SERVER_PORT
              value: "9054"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: ca-dealer
            # - name: FABRIC_CA_HOME
            #   value: "/etc/hyperledger/fabric-ca-server"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/dealer
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
