apiVersion: v1
kind: Service
metadata:
  name: ca-dealer
  labels:
    app: ca-dealer
spec:
  selector:
    app: ca-dealer
  type: ClusterIP
  ports:
    - port: 9054
      targetPort: 9054
      protocol: TCP
