apiVersion: v1
kind: Service
metadata:
  name: ca-mvd
  labels:
    app: ca-mvd
spec:
  selector:
    app: ca-mvd
  type: ClusterIP
  ports:
    - port: 7054
      targetPort: 7054
      protocol: TCP
